spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flights
    username: springstudent
    password: springstudent
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true

